INCLUDE(ExternalProject)

#message("CMAKE_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}")
ExternalProject_Add(
    clew-external
    SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/clew
    PREFIX ${CMAKE_BINARY_DIR}/clew
    CMAKE_CACHE_ARGS 
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
    -DBUILD_SHARED_LIBRARY:BOOL=ON
    -DBUILD_TESTS:BOOL=OFF
    -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
    )

ADD_LIBRARY(clew SHARED IMPORTED)
SET_PROPERTY(TARGET clew PROPERTY IMPORTED_LOCATION "${CMAKE_INSTALL_PREFIX}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}clew${CMAKE_SHARED_LIBRARY_SUFFIX}")
SET_PROPERTY(TARGET clew PROPERTY IMPORTED_IMPLIB "${CMAKE_INSTALL_PREFIX}/lib/clew.lib")
ADD_DEPENDENCIES(clew clew-external)
SET(CLEW_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/clew/include)
#message("lib path ${CMAKE_INSTALL_PREFIX}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}clew${CMAKE_SHARED_LIBRARY_SUFFIX}")
SET(CLEW_LIBRARIES ${CMAKE_INSTALL_PREFIX}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}clew${CMAKE_SHARED_LIBRARY_SUFFIX})
SET(CLEW_FOUND ON)

