INCLUDE(ExternalProject)

#message("CMAKE_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}")
ExternalProject_Add(
    clew-external
    STAMP_DIR ${CMAKE_BINARY_DIR}/clew/stamp
    SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/clew
    PREFIX ${CMAKE_BINARY_DIR}/clew
    INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
    CMAKE_CACHE_ARGS 
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
    -DBUILD_SHARED_LIBRARY:BOOL=ON
    -DBUILD_TESTS:BOOL=OFF
    -DADD_RPATH:BOOL=ON
    -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
    )

ADD_LIBRARY(clew SHARED IMPORTED)
ADD_DEPENDENCIES(clew clew-external)
#SET_PROPERTY(TARGET clew PROPERTY IMPORTED_LOCATION "${CMAKE_INSTALL_PREFIX}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}clew${CMAKE_SHARED_LIBRARY_SUFFIX}")
#SET_PROPERTY(TARGET clew PROPERTY IMPORTED_IMPLIB "${CMAKE_INSTALL_PREFIX}/lib/clew.lib")
SET(clew_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/clew/include ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/clew/include/proxy-opencl)
#message("lib path ${CMAKE_INSTALL_PREFIX}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}clew${CMAKE_SHARED_LIBRARY_SUFFIX}")
#if(WIN32)
#	SET(clew_LIBRARIES ${CMAKE_INSTALL_PREFIX}/lib/clew.lib)
#else()
#	SET(clew_LIBRARIES ${CMAKE_INSTALL_PREFIX}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}clew${CMAKE_SHARED_LIBRARY_SUFFIX})
#endif()
#SET(clew_FOUND ON)

if(WIN32)
set_target_properties(clew PROPERTIES
  #INSTALL_RPATH ${CMAKE_INSTALL_PREFIX}/lib/clew.lib
  IMPORTED_LOCATION ${CMAKE_INSTALL_PREFIX}/lib/clew.lib
)
else()
set_target_properties(clew PROPERTIES
  #MACOSX_RPATH ${CMAKE_INSTALL_PREFIX}/lib/
  #INSTALL_RPATH ${CMAKE_INSTALL_PREFIX}/lib/
  IMPORTED_LOCATION ${CMAKE_INSTALL_PREFIX}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}clew${CMAKE_SHARED_LIBRARY_SUFFIX}
)
endif()

add_custom_target(clew_delete_stamp ALL 
  COMMAND ${CMAKE_COMMAND} -E  remove_directory "${CMAKE_BINARY_DIR}/clew/stamp"
)
add_dependencies(clew-external clew_delete_stamp)

